# Generated by Django 3.0.3 on 2020-06-12 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructionid', models.CharField(max_length=20)),
                ('case_ref_no', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
                ('candidate_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('stay_period', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
