# Generated by Django 3.0.3 on 2020-06-12 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excl',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='excl',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='excl',
            name='case_ref_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='excl',
            name='client_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='excl',
            name='instructionid',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='excl',
            name='stay_period',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
