# Generated by Django 3.0.3 on 2020-06-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200612_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excl',
            name='stay_period',
            field=models.DateField(blank=True, max_length=20),
        ),
    ]
